#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="${TMPDIR:-/tmp}/snipefeed-offline-deps"
cd "$ROOT"

echo "== SnipeFeed qpackages-independent builder =="
echo "Project: $ROOT"

# Tiny VMs (such as 512 MB DigitalOcean droplets) need swap for clang/codegen.
if [[ -r /proc/meminfo ]] && command -v swapon >/dev/null 2>&1; then
  mem_kb="$(awk '/MemTotal:/ {print $2}' /proc/meminfo)"
  swap_kb="$(awk '/SwapTotal:/ {print $2}' /proc/meminfo)"
  if [[ "${mem_kb:-0}" -lt 1000000 && "${swap_kb:-0}" -lt 1000000 && "$(id -u)" -eq 0 ]]; then
    echo "Adding 2 GB swap for this low-memory VM..."
    if command -v fallocate >/dev/null 2>&1; then
      fallocate -l 2G /swapfile
    else
      dd if=/dev/zero of=/swapfile bs=1M count=2048 status=progress
    fi
    chmod 600 /swapfile
    mkswap /swapfile >/dev/null
    swapon /swapfile
  fi
fi

# Basic tooling. qpm is already expected to be installed; it is only used for the NDK.
missing=()
for c in git curl cmake ninja python3 zip qpm; do
  command -v "$c" >/dev/null 2>&1 || missing+=("$c")
done
if ((${#missing[@]})); then
  echo "Missing required tools: ${missing[*]}"
  if [[ "$(id -u)" -eq 0 ]] && command -v apt-get >/dev/null 2>&1; then
    echo "Installing standard build tools..."
    apt-get update
    apt-get install -y git curl cmake ninja-build python3 zip ca-certificates
  fi
fi
for c in git curl cmake ninja python3 zip qpm; do
  command -v "$c" >/dev/null 2>&1 || { echo "ERROR: $c is still missing"; exit 1; }
done

rm -rf "$TMP" "$ROOT/extern" "$ROOT/build" "$ROOT/SnipeFeed.qmod"
mkdir -p "$TMP" "$ROOT/extern/includes" "$ROOT/extern/libs"

clone_headers() {
  local id="$1" repo="$2" branch="$3"
  local dir="$TMP/$id"
  echo "-- headers: $id ($branch)"
  git clone -q --depth 1 --branch "$branch" --recurse-submodules --shallow-submodules "$repo" "$dir"
  local shared
  shared="$(python3 - "$dir/qpm.json" <<'PY'
import json, sys
with open(sys.argv[1], encoding='utf-8') as f:
    print(json.load(f).get('sharedDir', 'shared'))
PY
)"
  [[ -d "$dir/$shared" ]] || { echo "ERROR: $id sharedDir '$shared' not found"; exit 1; }
  mkdir -p "$ROOT/extern/includes/$id"
  cp -a "$dir/$shared" "$ROOT/extern/includes/$id/$shared"
}

download_lib() {
  local url="$1" name="$2"
  echo "-- library: $name"
  curl -fL --retry 5 --retry-delay 2 --connect-timeout 20 "$url" -o "$ROOT/extern/libs/$name"
}

# Exact source branches recorded by qpm.shared.json.
clone_headers custom-types https://github.com/QuestPackageManager/Il2CppQuestTypePatching.git version/v0_18_4
clone_headers rapidjson-macros https://github.com/Metalit/RapidjsonMacros.git version/v2_1_0
clone_headers bs-cordl https://github.com/QuestPackageManager/bs-cordl.git version/v4008_0_0
clone_headers paper2_scotland2 https://github.com/Fernthedev/paperlog.git version/v4_8_0
clone_headers tinyxml2 https://github.com/MillzyDev/NDK-tinyxml2.git version/v10_0_0
clone_headers songcore https://github.com/raineaeternal/Quest-SongCore.git version/v1_1_26
clone_headers config-utils https://github.com/darknight1050/config-utils.git version/v2_0_3
clone_headers libcurl https://github.com/darknight1050/openssl-curl-android.git version-v8.5.0
clone_headers beatsaber-hook https://github.com/QuestPackageManager/beatsaber-hook.git version/v6_4_2
clone_headers bsml https://github.com/bsq-ports/Quest-BSML.git version/v0_4_55
clone_headers scotland2 https://github.com/sc2ad/scotland2.git version/v0_1_7

# fmt 11.0.2 is an indirect header-only dependency. QPM normally exposes it as
# extern/includes/fmt/fmt/include.
echo "-- headers: fmt 11.0.2"
git clone -q --depth 1 --branch 11.0.2 https://github.com/fmtlib/fmt.git "$TMP/fmt-upstream"
mkdir -p "$ROOT/extern/includes/fmt/fmt"
cp -a "$TMP/fmt-upstream/include" "$ROOT/extern/includes/fmt/fmt/include"

# libil2cpp 0.4.0 is a header-only QPM package. Beat Saber 1.40.8 uses
# Unity 2021.3.16f1, so use the matching public Unity libil2cpp snapshot.
echo "-- headers: libil2cpp (Unity 2021.3.16f1)"
git clone -q --depth 1 --filter=blob:none --sparse https://github.com/MlgmXyysd/libil2cpp.git "$TMP/libil2cpp-upstream"
git -C "$TMP/libil2cpp-upstream" sparse-checkout set libil2cpp/Unity_2021.3/2021.3.16f1
mkdir -p "$ROOT/extern/includes/libil2cpp/il2cpp/libil2cpp"
cp -a "$TMP/libil2cpp-upstream/libil2cpp/Unity_2021.3/2021.3.16f1/." "$ROOT/extern/includes/libil2cpp/il2cpp/libil2cpp/"
# These are the two extra include roots generated by QPM. Most mod compilation
# only consumes libil2cpp headers directly; create the roots so CMake has the
# expected layout. If a dependency actually includes Baselib, the compiler will
# tell us and CI will catch it.
mkdir -p "$ROOT/extern/includes/libil2cpp/il2cpp/external/baselib/Include"
mkdir -p "$ROOT/extern/includes/libil2cpp/il2cpp/external/baselib/Platforms/Android/Include"

# Only direct, non-header-only dependencies are linked into SnipeFeed.
download_lib https://github.com/QuestPackageManager/Il2CppQuestTypePatching/releases/download/v0.18.4/libcustom-types.so libcustom-types.so
download_lib https://github.com/Fernthedev/paperlog/releases/download/v4.8.0/libpaper2_scotland2.so libpaper2_scotland2.so
download_lib https://github.com/raineaeternal/Quest-SongCore/releases/download/v1.1.26/libsongcore.so libsongcore.so
download_lib https://github.com/darknight1050/openssl-curl-android/releases/download/v8.5.0/libcurl.a libcurl.a
download_lib https://github.com/QuestPackageManager/beatsaber-hook/releases/download/v6.4.2/libbeatsaber-hook.so libbeatsaber-hook.so
download_lib https://github.com/bsq-ports/Quest-BSML/releases/download/v0.4.55/libbsml.so libbsml.so
download_lib https://github.com/sc2ad/scotland2/releases/download/v0.1.7/libsl2.so libsl2.so

echo "== Resolving Android NDK =="
qpm ndk resolve -d

echo "== Compiling =="
cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build
CMAKE_BUILD_PARALLEL_LEVEL=1 cmake --build build

test -s build/libsnipefeed.so || { echo "ERROR: build/libsnipefeed.so was not produced"; exit 1; }

echo "== Packaging SnipeFeed.qmod =="
rm -f SnipeFeed.qmod
(
  cd "$ROOT"
  zip -j -q SnipeFeed.qmod mod.json build/libsnipefeed.so
)

echo
echo "SUCCESS"
ls -lh "$ROOT/build/libsnipefeed.so" "$ROOT/SnipeFeed.qmod"
echo "QMOD: $ROOT/SnipeFeed.qmod"
